#pragma once

#include "vdsim/types.hpp"

#include <cmath>

namespace vdsim {

/**
 * Orthonormal tire contact frame expressed in an arbitrary parent frame.
 *
 * The caller supplies the injected road normal and wheel-forward direction in
 * the same frame.  The construction is exact for finite bank angles:
 * `z_c = unit(normal)`, `x_c = unit(x_w - z_c*(x_w dot z_c))`, and
 * `y_c = z_c cross x_c`.  No small-angle approximation or planar fallback is
 * used.  A degenerate input produces `valid=false` and must be treated as no
 * contact by the dynamics caller.
 */
struct ContactFrame {
    Vec3 x_c {Vec3::Zero()};
    Vec3 y_c {Vec3::Zero()};
    Vec3 z_c {Vec3::Zero()};
    bool valid {false};

    /** Resolve a parent-frame velocity into longitudinal, lateral, normal components. */
    Vec3 resolve_velocity(const Vec3& parent_velocity) const noexcept {
        return Vec3(parent_velocity.dot(x_c),
                    parent_velocity.dot(y_c),
                    parent_velocity.dot(z_c));
    }

    /** Rotate a contact-frame tangential force into the parent frame. */
    Vec3 tangential_force(double Fx, double Fy) const noexcept {
        return Vec3(Fx * x_c.x() + Fy * y_c.x(),
                    Fx * x_c.y() + Fy * y_c.y(),
                    Fx * x_c.z() + Fy * y_c.z());
    }

    /** Return the parent-frame vector for normal-load magnitude Fz. */
    Vec3 normal_force(double Fz) const noexcept { return Fz * z_c; }
};

/**
 * Build the right-handed tire contact frame without a flat-road fallback.
 *
 * The exact canonical-flat branch preserves the established bit-level L3/L4
 * path for `normal=(0,0,1)` while representing the same analytic orthonormal
 * basis generated by wheel-heading sine and cosine.
 */
inline ContactFrame make_contact_frame(const Vec3& injected_normal,
                                       const Vec3& wheel_forward) noexcept {
    ContactFrame frame;
    if (!injected_normal.allFinite() || !wheel_forward.allFinite()) return frame;
    const double normal_norm = injected_normal.norm();
    if (!(normal_norm > 1e-12)) return frame;

    if (injected_normal.x() == 0.0 && injected_normal.y() == 0.0
        && injected_normal.z() > 0.0 && wheel_forward.z() == 0.0) {
        const double forward_norm = std::hypot(wheel_forward.x(), wheel_forward.y());
        if (!(forward_norm > 1e-12)) return frame;
        // Heading is supplied as (cos, sin, 0); retaining those components is
        // algebraically unit length and preserves the frozen flat-road path.
        frame.x_c = wheel_forward;
        frame.y_c = Vec3(-wheel_forward.y(), wheel_forward.x(), 0.0);
        frame.z_c = Vec3::UnitZ();
        frame.valid = true;
        return frame;
    }

    frame.z_c = injected_normal / normal_norm;
    const Vec3 projected = wheel_forward
                         - frame.z_c * wheel_forward.dot(frame.z_c);
    const double projected_norm = projected.norm();
    if (!(projected_norm > 1e-12)) {
        frame = ContactFrame{};
        return frame;
    }
    frame.x_c = projected / projected_norm;
    frame.y_c = frame.z_c.cross(frame.x_c);
    const double lateral_norm = frame.y_c.norm();
    if (!(lateral_norm > 1e-12) || !frame.y_c.allFinite()) {
        frame = ContactFrame{};
        return frame;
    }
    frame.y_c /= lateral_norm;
    frame.valid = true;
    return frame;
}

}  // namespace vdsim
