id: chassis.5link_rear_sports
type: chassis
version: 1
schema: kinematics_l3_native_v1
label: 5link_rear_sports kinematics
tags:
- chassis
body:
  path: parts/susp_kinematics/kin/5link_rear_sports.yaml
