id: susp.5link_rear_sports
type: susp_kinematics
version: 1
schema: kinematics_l3_native_v1
label: 5link_rear_sports kinematics
tags:
- susp_kinematics
body:
  path: parts/susp_kinematics/kin/5link_rear_sports.yaml
