type: double_wishbone
side: left
wheel:
  center:
  - 0.0
  - 0.79
  - 0.33
  spin_axis:
  - 0.0
  - 1.0
  - 0.0
  static_radius: 0.33
lca:
  chassis_front:
  - 0.15
  - 0.3
  - 0.08
  chassis_rear:
  - -0.18
  - 0.3
  - 0.08
  knuckle:
  - -0.02
  - 0.75
  - 0.15
uca:
  chassis_front:
  - 0.08
  - 0.45
  - 0.32
  chassis_rear:
  - -0.22
  - 0.45
  - 0.32
  knuckle:
  - -0.01
  - 0.7
  - 0.55
tie_rod:
  rack:
  - -0.3
  - 0.35
  - 0.18
  knuckle:
  - -0.3
  - 0.74
  - 0.21
spring_damper:
  chassis:
  - -0.05
  - 0.45
  - 0.5
  lca:
  - -0.05
  - 0.55
  - 0.13
