#!/usr/bin/env python3
"""VDSim validation evidence bundle — one command, one credibility artifact.

Aggregates the validation suite into a dated results folder:
  1. analytic + ISO + cross-model + tire-parity ctests  (pass/fail)
  2. MF2002 vs Chrono Pac02 tire table                  (tools/tire_validation.py)
  3. ISO 7401 / 4138 / 3888-2 figures                   (apps/validation/run_validation.py)
  4. a single summary.md tying it together

Run:
    python3 tools/validation_report.py
    python3 tools/validation_report.py --out results/validation/2026-06-16

The report is the reproducible evidence backing docs/VALIDATION.md.
"""
import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BUILD = REPO / "build"

# Validation-tagged ctest name regex (analytic + ISO + cross-model + parity).
CTEST_FILTER = ("BicycleSteadyState|LongScenarios|WeightTransfer|FourteenDOF|"
                "Iso8608|IsoBaseline|ChronoPac02Parity|BeltTire|BeltValidation|"
                "SevenDOF|ControlDispatch")


def run_ctests(out_dir: Path) -> dict:
    print("[1/3] Running validation ctests ...")
    log = out_dir / "ctest.log"
    proc = subprocess.run(
        ["ctest", "-R", CTEST_FILTER, "--output-on-failure"],
        cwd=BUILD, capture_output=True, text=True)
    log.write_text(proc.stdout + "\n" + proc.stderr)
    # Parse the "N% tests passed, M failed out of K" summary line.
    summary = {"passed": 0, "failed": 0, "total": 0, "ok": proc.returncode == 0}
    for line in proc.stdout.splitlines():
        if "tests passed" in line and "out of" in line:
            # e.g. "100% tests passed, 0 tests failed out of 64"
            try:
                summary["failed"] = int(line.split(",")[1].split()[0])
                summary["total"]  = int(line.split("out of")[1].strip())
                summary["passed"] = summary["total"] - summary["failed"]
            except (IndexError, ValueError):
                pass
    print(f"      {summary['passed']}/{summary['total']} validation ctests passed")
    return summary


def run_tire_parity(out_dir: Path) -> dict:
    print("[2/3] Tire parity (MF2002 vs Chrono Pac02) ...")
    tir = REPO / "external/chrono_parity/sample_pac02.tir"
    ref = REPO / "external/chrono_parity/reference/pac02_reference.csv"
    if not (tir.exists() and ref.exists()):
        print("      skipped — no Chrono reference data")
        return {}
    subprocess.run(
        [sys.executable, str(REPO / "tools/tire_validation.py"),
         "--tir", str(tir), "--ref", str(ref),
         "--out", str(out_dir / "tire")],
        cwd=REPO, capture_output=True, text=True,
        env={"PYTHONPATH": f"{BUILD/'python'}:{REPO/'python'}", "PATH": "/usr/bin:/bin"})
    summ = out_dir / "tire" / "summary.json"
    if summ.exists():
        data = json.loads(summ.read_text())
        pl = data.get("pure_longitudinal_Fx", {})
        print(f"      pure-long Fx mean {pl.get('mean_pct')}% (gate {pl.get('gate_pct')}%)")
        return data
    return {}


def run_iso_figures(out_dir: Path) -> bool:
    print("[3/3] ISO maneuver figures (7401 / 4138 / 3888-2) ...")
    r = subprocess.run(
        [sys.executable, str(REPO / "apps/validation/run_validation.py"),
         "--out", str(out_dir / "iso")],
        cwd=REPO, capture_output=True, text=True,
        env={"PYTHONPATH": f"{BUILD/'python'}:{REPO/'python'}", "PATH": "/usr/bin:/bin"})
    figs = list((out_dir / "iso").glob("*.png")) if (out_dir / "iso").exists() else []
    print(f"      {len(figs)} figure(s) written" if figs
          else "      no figures (matplotlib missing?)")
    return len(figs) > 0


def write_summary(out_dir: Path, ct: dict, tire: dict, figs: bool):
    lines = [
        f"# VDSim validation evidence — {date.today().isoformat()}",
        "",
        "Reproducible artifact backing `docs/VALIDATION.md`. Generated by "
        "`tools/validation_report.py`.",
        "",
        "## 1. Automated benchmarks (ctest)",
        "",
        f"- Validation subset: **{ct.get('passed',0)}/{ct.get('total',0)}** passed "
        f"({'PASS' if ct.get('ok') else 'FAIL'})",
        "- Covers: analytic (bicycle yaw, drag coast, weight transfer), ISO 7401/4138/3888-2 "
        "baseline gate, ISO 8608 PSD, L1↔L2↔L3 cross-model, belt transient, Chrono Pac02 parity.",
        "- Full log: `ctest.log`",
        "",
        "## 2. Tire parity — MF2002 vs Chrono Pac02 (independent BSD-3)",
        "",
    ]
    if tire:
        lines.append("| regime | n | mean % | max % | gate |")
        lines.append("|---|---|---|---|---|")
        for key, label in [("pure_longitudinal_Fx", "Pure-long Fx"),
                           ("pure_lateral_Fy",      "Pure-lat Fy"),
                           ("combined_Fx",          "Combined Fx"),
                           ("combined_Fy",          "Combined Fy")]:
            s = tire.get(key, {})
            g = s.get("gate_pct"); gate = f"<{g:.0f}%" if g else "report"
            lines.append(f"| {label} | {s.get('n','-')} | {s.get('mean_pct','-')} "
                         f"| {s.get('max_pct','-')} | {gate} |")
        lines.append("")
        lines.append("Per-point CSV: `tire/`")
    else:
        lines.append("_skipped — no Chrono reference data present._")
    lines += [
        "",
        "## 3. ISO maneuver figures",
        "",
        ("ISO 7401 step-steer, 4138 understeer, 3888-2 DLC plots in `iso/`."
         if figs else "_figures unavailable (matplotlib not installed)._"),
        "",
        "## Honest gaps",
        "",
        "- No real-vehicle cross-validation (CarMaker/CarSim/Adams data confidential).",
        "- Tire combined-slip cross-terms differ from Pac02 (friction-ellipse weighting; reported).",
        "- No tire thermal / wear / turn-slip.",
    ]
    (out_dir / "summary.md").write_text("\n".join(lines) + "\n")
    print(f"\nEvidence bundle → {out_dir}/summary.md")


def main():
    ap = argparse.ArgumentParser(description="VDSim validation evidence bundle")
    ap.add_argument("--out", default=f"results/validation/{date.today().isoformat()}")
    args = ap.parse_args()
    out = (REPO / args.out) if not Path(args.out).is_absolute() else Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    ct   = run_ctests(out)
    tire = run_tire_parity(out)
    figs = run_iso_figures(out)
    write_summary(out, ct, tire, figs)
    sys.exit(0 if ct.get("ok") else 1)


if __name__ == "__main__":
    main()
