id: vehicle.race_gt
version: 1
label: Race Gt
level: L3
parts:
  body: body.race_car
  aero: aero.race_car
  ride: ride.race_car
  tire: tire.default_pacejka
  brake: brake.race_car
  steering: steering.race_car
  drivetrain: drivetrain.race_car
  front_chassis: chassis.dw_front_sports
  rear_chassis: chassis.5link_rear_sports
overrides: {}
